In [52]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Dropout

In [54]:
data = pd.read_csv("Training.csv", sep=",")
data2 = pd.read_csv("Testing.csv", sep=',')

In [55]:
df = data.to_numpy()
df2 = data2.to_numpy()

In [56]:
print(df.shape)
print(df2.shape)

x_train = df[0:4920,0:132]
y_train = df[0:4920,132]

print(x_train)
print(y_train)

x_test = df2[0:42,0:132]
y_test = df2[0:42,132]
print(x_test)
print(y_test)

(4920, 134)
(42, 134)
[[1 1 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 1 1 1]]
['Fungal infection' 'Fungal infection' 'Fungal infection' ...
 'Urinary tract infection' 'Psoriasis' 'Impetigo']
[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 1 1 1]
 [1 1 0 ... 0 1 0]]
['Fungal infection' 'Allergy' 'GERD' 'Chronic cholestasis' 'Drug Reaction'
 'Peptic ulcer diseae' 'AIDS' 'Diabetes ' 'Gastroenteritis'
 'Bronchial Asthma' 'Hypertension ' 'Migraine' 'Cervical spondylosis'
 'Paralysis (brain hemorrhage)' 'Jaundice' 'Malaria' 'Chicken pox'
 'Dengue' 'Typhoid' 'hepatitis A' 'Hepatitis B' 'Hepatitis C'
 'Hepatitis D' 'Hepatitis E' 'Alcoholic hepatitis' 'Tuberculosis'
 'Common Cold' 'Pneumonia' 'Dimorphic hemmorhoids(piles)' 'Heart attack'
 'Varicose veins' 'Hypothyroidism' 'Hyperthyroidism' 'Hypoglycemia'
 'Osteoarthristis' 'Arthritis' '(vertigo) Paroymsal  Positional Vertigo'
 'Acne' 'Ur

In [57]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')

In [58]:
train_labels = []
for val in y_train:
  count = 0
  for val2 in train_labels:
    if (val == val2):
      count += 1
  if count == 0:
    train_labels.append(val)

print(len(train_labels))

41


In [59]:
for val1 in range(len(y_train)):
  for val2 in range(len(train_labels)):
    if (y_train[val1] == train_labels[val2]):
      df[val1][133] = val2
#print(df)
train_encode = df[0:4920,133]
print(train_encode)

for val1 in range(len(y_test)):
  for val2 in range(len(train_labels)):
    if (y_test[val1] == train_labels[val2]):
      df2[val1][133] = val2
#print(df)
train_encode2 = df2[0:4920,133]
print(train_encode2)

[0 0 0 ... 38 39 40]
[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31 32 33 34 35 36 37 38 39 40 0]


In [60]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(4920, 132)
(4920,)
(42, 132)
(42,)


In [61]:
model = Sequential()
model.add(Dense(4920, input_dim=132, activation='relu'))
model.add(Dense(42, activation="softmax"))

In [62]:
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [63]:
train_encode = train_encode.astype('float32')
train_encode2 = train_encode2.astype('float32')

In [64]:
model.fit(x_train, train_encode, epochs=5)

Epoch 1/5
154/154 [==============================] - 3s 13ms/step - loss: 0.3135 - accuracy: 0.9705
Epoch 2/5
154/154 [==============================] - 2s 16ms/step - loss: 0.0017 - accuracy: 1.0000
Epoch 3/5
154/154 [==============================] - 3s 19ms/step - loss: 7.2565e-04 - accuracy: 1.0000
Epoch 4/5
154/154 [==============================] - 2s 13ms/step - loss: 3.8794e-04 - accuracy: 1.0000
Epoch 5/5
154/154 [==============================] - 2s 14ms/step - loss: 2.3133e-04 - accuracy: 1.0000


In [65]:
test_loss, test_acc = model.evaluate(x_test, train_encode2)

2/2 [==============================] - 0s 11ms/step - loss: 0.0476 - accuracy: 0.9762


In [73]:
final = int(test_acc*100)
print(str(final) + '%')

97%
